---
    
- hosts: master_node_1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_config:
      cluster.initial_master_nodes: "192.168.50.2, 192.168.50.3, 192.168.50.4"
      cluster.name: "production"
      network.host: "{{ ansible_eth1.ipv4.address }}, _local_"
      discovery.seed_hosts: "192.168.50.2:9300, 192.168.50.3:9300, 192.168.50.4:9300"
      http.port: 9200 
      transport.tcp.port: 9300
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_major_version: "7.x"
    es_version: "7.6.0"
    es_heap_size: "128m"
    es_cluster_name: "production"

- hosts: master_node_2
  roles:
    - role: elastic.elasticsearch
  vars:
    es_config:
      cluster.initial_master_nodes: "192.168.50.2, 192.168.50.3, 192.168.50.4"
      cluster.name: "production"
      network.host: "{{ ansible_eth1.ipv4.address }}, _local_"
      discovery.seed_hosts: "192.168.50.2:9300, 192.168.50.3:9300, 192.168.50.4:9300"
      http.port: 9200 
      transport.tcp.port: 9300
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_major_version: "7.x"
    es_version: "7.6.0"
    es_heap_size: "128m"
    es_cluster_name: "production"

- hosts: master_node_3
  roles:
    - role: elastic.elasticsearch
  vars:
    es_config:
      cluster.initial_master_nodes: "192.168.50.2, 192.168.50.3, 192.168.50.4"
      cluster.name: "production"
      network.host: "{{ ansible_eth1.ipv4.address }}, _local_"
      discovery.seed_hosts: "192.168.50.2:9300, 192.168.50.3:9300, 192.168.50.4:9300"
      http.port: 9200 
      transport.tcp.port: 9300
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_major_version: "7.x"
    es_version: "7.6.0"
    es_heap_size: "128m"
    es_cluster_name: "production"

- hosts: data_node_1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_config:
      cluster.initial_master_nodes: "192.168.50.2, 192.168.50.3, 192.168.50.4"
      cluster.name: "production"
      network.host: "{{ ansible_eth1.ipv4.address }}, _local_"
      discovery.seed_hosts: "192.168.50.2:9300, 192.168.50.3:9300, 192.168.50.4:9300"
      http.port: 9200 
      transport.tcp.port: 9300
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_major_version: "7.x"
    es_version: "7.6.0"
    es_heap_size: "128m"
    es_cluster_name: "production"
